/* Generated By:JavaCC: Do not edit this line. JBLParserTreeConstants.java Version 5.0 */
package jbitlanguage;

public interface JBLParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVARDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTORNODE = 4;
  public int JJTANDNODE = 5;
  public int JJTBITWISEORNODE = 6;
  public int JJTBITWISEXORNODE = 7;
  public int JJTBITWISEANDNODE = 8;
  public int JJTEQNODE = 9;
  public int JJTNENODE = 10;
  public int JJTLTNODE = 11;
  public int JJTGTNODE = 12;
  public int JJTLENODE = 13;
  public int JJTGENODE = 14;
  public int JJTADDNODE = 15;
  public int JJTSUBTRACTNODE = 16;
  public int JJTMULNODE = 17;
  public int JJTDIVNODE = 18;
  public int JJTMODNODE = 19;
  public int JJTBITWISECOMPLNODE = 20;
  public int JJTNOTNODE = 21;
  public int JJTGLOBALCUR = 22;
  public int JJTGLOBALRANDOM = 23;
  public int JJTGLOBALENEMY = 24;
  public int JJTID = 25;
  public int JJTINTCONSTNODE = 26;
  public int JJTTRUENODE = 27;
  public int JJTFALSENODE = 28;
  public int JJTBLOCK = 29;
  public int JJTSTATEMENTEXPRESSION = 30;
  public int JJTIFSTATEMENT = 31;
  public int JJTWHILESTATEMENT = 32;
  public int JJTREADSTATEMENT = 33;
  public int JJTWRITESTATEMENT = 34;
  public int JJTRETURNSTATEMENT = 35;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "VarDeclaration",
    "void",
    "Assignment",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "BitwiseComplNode",
    "NotNode",
    "GlobalCur",
    "GlobalRandom",
    "GlobalEnemy",
    "Id",
    "IntConstNode",
    "TrueNode",
    "FalseNode",
    "Block",
    "StatementExpression",
    "IfStatement",
    "WhileStatement",
    "ReadStatement",
    "WriteStatement",
    "ReturnStatement",
  };
}
/* JavaCC - OriginalChecksum=3c6de9049b4ad637f1d16c910ea17409 (do not edit this line) */
