/* Generated By:JJTree&JavaCC: Do not edit this line. JBLParserConstants.java */
package jbitlanguage;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JBLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int BOOL = 7;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 8;
  /** RegularExpression Id. */
  int CUR = 9;
  /** RegularExpression Id. */
  int ENEMY = 10;
  /** RegularExpression Id. */
  int RANDOM = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 47;
  /** RegularExpression Id. */
  int LETTER = 48;
  /** RegularExpression Id. */
  int DIGIT = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER_LITERAL>",
    "\"CUR\"",
    "\"ENEMY\"",
    "\"RANDOM\"",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"read\"",
    "\"write\"",
    "\"return\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
